Fix BILLY_SERVER URL and enhance manifest generation
Updated BILLY_SERVER URL and added manifest generation steps.

diff --git a/.github/workflows/main-ia03.yml b/.github/workflows/main-ia03.yml
--- a/.github/workflows/main-ia03.yml
+++ b/.github/workflows/main-ia03.yml
@@ -82,4 +82,23 @@ jobs:
 
       - name: Manifest Generation SBOM
         env:
-          BILLY_SERVER: https://billy.codesec.aquasec_
+          BILLY_SERVER: https://billy.codesec.aquasec.com
+        run: |
+          docker image ls
+
+          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/latest/download/install.sh.checksum
+
+          if ! sha256sum --check install.sh.checksum; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+
+          BINDIR="." sh install.sh
+          rm -f install.sh install.sh.checksum
+
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "stalibali/prg-image:${{ github.sha }}"
