Update SBOM generation script URLs and artifact path

diff --git a/.github/workflows/main-ia03.yml b/.github/workflows/main-ia03.yml
--- a/.github/workflows/main-ia03.yml
+++ b/.github/workflows/main-ia03.yml
@@ -61,19 +61,23 @@ jobs:
       - name: Manifest Generation SBOM
         run: |
           export BILLY_SERVER=https://billy.codesec.aquasec.com
-          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+
+          curl -sLo install.sh https://download.codesec.aquasec.com/billy/install.sh
           curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
-          if ! cat install.sh.checksum | sha256sum --check; then
-          echo "install.sh checksum failed"
-          exit 1
+
+          if ! sha256sum --check install.sh.checksum; then
+            echo "install.sh checksum failed"
+            exit 1
           fi
+
           BINDIR="." sh install.sh
           rm install.sh install.sh.checksum
+
           ./billy generate \
-            --access-token "${{ secrets.GITHUB_TOKEN }}" \ 
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
             --aqua-key "${{ secrets.AQUA_KEY }}" \
             --aqua-secret "${{ secrets.AQUA_SECRET }}" \
-            --artifact-path "${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}" 
+            --artifact-path "docker://prg-image:${{ github.sha }}"
 
             # The docker image name:tag of the newly built image
             # --artifact-path "my-image-name:${{ env.tag-version }}" 
