Update SBOM generation process in workflow
Replaced SBOM generation with a new manifest generation step using Billy.

diff --git a/.github/workflows/main-ia03.yml b/.github/workflows/main-ia03.yml
--- a/.github/workflows/main-ia03.yml
+++ b/.github/workflows/main-ia03.yml
@@ -65,18 +65,24 @@ jobs:
           docker tag prg-image:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}
 
-      # Optional: Generate SBOM from filesystem (repo/code level)
-      - name: Generate SBOM with Trivy OSS
-        uses: aquasecurity/trivy-action@master
-        with:
-          scan-type: fs
-          format: cyclonedx
-          output: sbom.cdx.json
-          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
+      - name: Manifest Generation SBOM
+        run: |
+          export BILLY_SERVER=https://billy.codesec.aquasec.com
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | sha256sum --check; then
+          echo "install.sh checksum failed"
+          exit 1
+          fi
+          BINDIR="." sh install.sh
+          rm install.sh install.sh.checksum
+          ./billy generate \
+            --access-token "${{ secrets.GITHUB_TOKEN }}" \
+            --aqua-key "${{ secrets.AQUA_KEY }}" \
+            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+            --artifact-path "${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}" 
 
-      - name: Upload SBOM Artifact
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: sbom
-          path: sbom.cdx.json
+            # The docker image name:tag of the newly built image
+            # --artifact-path "my-image-name:${{ env.tag-version }}" 
+            # OR the path to the root folder of your project. I.e my-repo/my-app 
+            # --artifact-path "${{env.MY_APP_ROOT}}"
